name: Auth CD
on:
  push:
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/auth/
    permissions:
      contents: 'read'
      packages: 'write'
    env:
      REGISTRY: ghcr.io
      REPO_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Web to ghcr
        uses: docker/build-push-action@v3
        with:
          file: platform/auth/Dockerfile
          context: platform/auth/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-auth:${{ steps.vars.outputs.tag }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}

