name: .NET Server CI
concurrency:
  group: platform-server-ci-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
    - '**'
    paths:
    - 'platform/server/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/server/
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
